run_hash: my-eval-batch-v2 # run name
hash_env_var: BEAKER_RUNNER_HASH # run hash

repos:
  - url: https://github.com/allenai/OLMo-core
    branch: ladder-adapt
    install: "uv pip install -e '.[beaker]'"

commands:
  - command: "python -m olmo_core.launch --run-name test-run"
    libs:
      - OLMo-core
  - "echo 'Experiment: test/foo â†’ https://beaker.org/ex/FAKE123' && sleep 1"
